; draw the tree illustrating the process generated by the count-change procedure in making change for 11 cents.
; what are the orders of growth of the space and number of steps used by this processu as the amount to be changed increases?

(load-option 'format)
(define (count-change amount)
  (begin
    (set! calls 0)
    (let ((result (cc amount 5)))
      (begin
        (display calls)
        (newline)
        result))))

(define calls 0)

(define (cc amount kinds-of-coins)
  (begin
    (set! calls (+ calls 1))
    (let ((result 
            (cond ((= amount 0) 1)
                  ((or (< amount 0) (= kinds-of-coins 0)) 0)
                  (else (+ (cc amount (- kinds-of-coins 1))
                           (cc (- amount (first-denomination kinds-of-coins)) kinds-of-coins))))))
      result)))


(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(define (up-to i n step)
  (cond
    ((>= i n) (cons n ()))
    (else (cons i (up-to (+ i step) n step)))))
